title: Jingyu-Sun's Homepage
page-top-title: Stone Sun
top-section-bg-text: Be what you wanna be
home-subtitle: Jingyu Sun&ensp;|&ensp;Stone
copyright-text: '&copy; Jingyu Sun 2025. All Rights Reserved.'
